version = 1

test_patterns = ["**/tests/**"]

exclude_patterns = [
  "*.md",
  "*.yaml",
  "*.yml"
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"