version: "3.2"
services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2022-05-04T07-45-27Z
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /data/minio/data:/data
    restart: "always"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  onesphere:
    container_name: onesphere
    networks:
      - traefik
    image: ghcr.io/ethermeta-org/onesphere:14
    extra_hosts:
      - host.docker.internal:host-gateway
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "20"
    ports:
      - "38069:8069"
    volumes:
      - /data/onesphere/data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    restart: "always"
    entrypoint: ["odoo",--proxy-mode,"--load","oneshare_odoo_modify,smile_redis_session_store,l10n_cn_city","--limit-time-cpu","3600","--limit-time-real", "3600","--no-database-list","--limit-time-real-cron", "0","--workers","8","--without-demo","all", "--load-language", "zh_CN"]
    environment:
      - ODOO_HTTP_SOCKET_TIMEOUT=20
      - ENV_TIMESCALE_ENABLE=true #使能timescaledb功能
      - ENV_REDIS_ENABLE=false
      - ENV_RUNTIME_ENV=prod
      - ENV_DOCKER_URL=unix://var/run/docker.sock
networks:
  traefik:
    external: true